server:
  port: 8080

spring:
  application:
    name: graph-mail-backend

  data:
    mongodb:
      uri: mongodb+srv://johyerim01:uLjEL2Orw3VaLL3I@cluster0.1lfd3.mongodb.net/mydatabase?retryWrites=true&w=majority&appName=Cluster0
      database: mydatabase

  security:
    oauth2:
      client:
        registration:
          microsoft:
            client-id: 20c79eba-0a76-40aa-9598-75297ae6146f
            client-secret: 3qm8Q~Gj2GbBdnAIywff1azUtq_w23VFBN2rMdpj
            redirect-uri: "{baseUrl}/login/oauth2/code/microsoft"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
              - https://graph.microsoft.com/User.Read
              - https://graph.microsoft.com/Mail.Send
              - https://graph.microsoft.com/Mail.Read

        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
            user-name-attribute: sub
